// <auto-generated />
using System;
using Hiof.DotNetCourse.V2023.Group14.UserAccountService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hiof.DotNetCourse.V2023.Group14.UserAccountService.Migrations.UserAccount
{
    [DbContext(typeof(UserAccountContext))]
    [Migration("20230223095723_Seed2")]
    partial class Seed2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hiof.DotNetCourse.V2023.Group14.ClassLibrary.Classes.V1.V1User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("country");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("first_name");

                    b.Property<string>("LangPreference")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("lang_preference");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("datetime")
                        .HasColumnName("last_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("password");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("registration_date");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("user_role");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("59890f58-7bce-47d1-a308-56a72f58c80a"),
                            City = "Seattle",
                            Country = "USA",
                            Email = "joojoo@gmail.com",
                            FirstName = "Jinkx",
                            LangPreference = "en",
                            LastActive = new DateTime(2023, 2, 23, 10, 57, 23, 541, DateTimeKind.Local).AddTicks(6348),
                            LastName = "Monsoon",
                            Password = "Itismonsoonseason!",
                            RegistrationDate = new DateTime(2023, 2, 23, 10, 57, 23, 541, DateTimeKind.Local).AddTicks(6307),
                            Role = "User",
                            UserName = "JinkxMonsoon"
                        },
                        new
                        {
                            Id = new Guid("e43fdf2b-523c-471d-8664-97c9d9ad6c11"),
                            City = "Toronto",
                            Country = "Canada",
                            Email = "b_hyteso@gmail.com",
                            FirstName = "Brooklyn",
                            LangPreference = "en",
                            LastActive = new DateTime(2023, 2, 23, 10, 57, 23, 541, DateTimeKind.Local).AddTicks(6354),
                            LastName = "Hytes",
                            Password = "CanadianTurkeyBacon",
                            RegistrationDate = new DateTime(2023, 2, 23, 10, 57, 23, 541, DateTimeKind.Local).AddTicks(6353),
                            Role = "User",
                            UserName = "QueenOfTheNorth"
                        },
                        new
                        {
                            Id = new Guid("7a5e9c16-e8b0-498a-bbce-c674503346e9"),
                            City = "Palm Springs",
                            Country = "USA",
                            Email = "bdelrio@yahoo.com",
                            FirstName = "Bianca",
                            LangPreference = "en",
                            LastActive = new DateTime(2023, 2, 23, 10, 57, 23, 541, DateTimeKind.Local).AddTicks(6358),
                            LastName = "Del Rio",
                            Password = "Baloney2123",
                            RegistrationDate = new DateTime(2023, 2, 23, 10, 57, 23, 541, DateTimeKind.Local).AddTicks(6357),
                            Role = "Admin",
                            UserName = "ClownBeauty"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
