trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: dotnet Hiof.DotNetCourse.V2023.Group14/Hiof.DotNetCourse.V2023.Group14.sln --configuration $(buildConfiguration)
  displayName: 'Compile and build the solution.'

- script: dotnete test
  displayName: 'Runs all tests currently in the repository.'
