trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: dotnet build Hiof.DotNetCourse.V2023.Group14/Hiof.DotNetCourse.V2023.Group14.sln
  displayName: 'Compile and build the solution.'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'Hiof.DotNetCourse.V2023.Group14/Hiof.DotNetCourse.V2023.Group14.sln'
    arguments: '--configuration $(buildConfiguration) --logger trx --results-directory $(Agent.TempDirectory)'
    publishTestResults: true
  displayName: 'Run all tests currently in the repository.'
  continueOnError: true

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Verifying all tests passed' 