trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: dotnet build Hiof.DotNetCourse.V2023.Group14/Hiof.DotNetCourse.V2023.Group14.sln
  displayName: 'Building the solution.'

- script: dotnet test Hiof.DotNetCourse.V2023.Group14/Hiof.DotNetCourse.V2023.Group14.sln --logger trx --results-directory Hiof.DotNetCourse.V2023.Group14/tests
  displayName: 'Running all tests currently in the repository.'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**\*.trx'
    failTaskOnFailedTests: true
    testRunTitle: 'Verifying all tests passed.' 