// <auto-generated />
using System;
using Hiof.DotNetCourse.V2023.Group14.ReadingGoalService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hiof.DotNetCourse.V2023.Group14.ReadingGoalService.Migrations
{
    [DbContext(typeof(ReadingGoalsContext))]
    partial class ReadingGoalsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hiof.DotNetCourse.V2023.Group14.ClassLibrary.Classes.V1.V1ReadingGoals", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("GoalCurrent")
                        .HasColumnType("int")
                        .HasColumnName("goal_curr");

                    b.Property<DateTime>("GoalEndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("goal_end");

                    b.Property<DateTime>("GoalStartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("goal_start");

                    b.Property<int>("GoalTarget")
                        .HasColumnType("int")
                        .HasColumnName("goal_target");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime")
                        .HasColumnName("last_updated");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("reading_goals", "dbo");

                    b.HasData(
                        new
                        {
                            Id = "1dd99ec1-aaae-4df5-b9e2-fc233a9e1dd9",
                            GoalCurrent = 5,
                            GoalEndDate = new DateTime(2023, 3, 21, 7, 43, 11, 453, DateTimeKind.Unspecified),
                            GoalStartDate = new DateTime(2023, 2, 21, 7, 43, 11, 453, DateTimeKind.Unspecified),
                            GoalTarget = 20,
                            LastUpdated = new DateTime(2023, 2, 21, 7, 43, 11, 453, DateTimeKind.Unspecified),
                            UserId = "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                        },
                        new
                        {
                            Id = "3b6c06da-250e-4f7a-b867-facbc6a48574",
                            GoalCurrent = 17,
                            GoalEndDate = new DateTime(2022, 12, 21, 7, 43, 11, 453, DateTimeKind.Unspecified),
                            GoalStartDate = new DateTime(2022, 10, 21, 7, 43, 11, 453, DateTimeKind.Unspecified),
                            GoalTarget = 20,
                            LastUpdated = new DateTime(2023, 2, 21, 7, 43, 11, 453, DateTimeKind.Unspecified),
                            UserId = "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                        },
                        new
                        {
                            Id = "c6050d5c-8b0a-402a-a020-7c2c4e82584a",
                            GoalCurrent = 1,
                            GoalEndDate = new DateTime(2022, 7, 21, 7, 43, 11, 453, DateTimeKind.Unspecified),
                            GoalStartDate = new DateTime(2022, 5, 21, 7, 43, 11, 453, DateTimeKind.Unspecified),
                            GoalTarget = 15,
                            LastUpdated = new DateTime(2023, 6, 21, 7, 43, 11, 453, DateTimeKind.Unspecified),
                            UserId = "54af86bf-346a-4cba-b36f-527748e1cb93"
                        },
                        new
                        {
                            Id = "273b0fd5-cf41-4089-8611-f41d8099992c",
                            GoalCurrent = 7,
                            GoalEndDate = new DateTime(2023, 4, 21, 7, 43, 11, 453, DateTimeKind.Unspecified),
                            GoalStartDate = new DateTime(2023, 1, 21, 7, 43, 11, 453, DateTimeKind.Unspecified),
                            GoalTarget = 20,
                            LastUpdated = new DateTime(2023, 2, 21, 11, 54, 29, 123, DateTimeKind.Unspecified),
                            UserId = "54af86bf-346a-4cba-b36f-527748e1cb93"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
