// <auto-generated />
using Hiof.DotNetCourse.V2023.Group14.UserAccountService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hiof.DotNetCourse.V2023.Group14.UserAccountService.Migrations
{
    [DbContext(typeof(DbOrmTestClassContext))]
    partial class DbOrmTestClassContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hiof.DotNetCourse.V2023.Group14.ClassLibrary.Classes.DbOrmTestClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.HasKey("Id");

                    b.ToTable("Tests", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 42,
                            Name = "Jonas"
                        },
                        new
                        {
                            Id = 2,
                            Age = 1,
                            Name = "Dobby the House Dog"
                        },
                        new
                        {
                            Id = 3,
                            Age = 743,
                            Name = "Margaret of Anjou"
                        },
                        new
                        {
                            Id = 4,
                            Age = 29,
                            Name = "Sam"
                        },
                        new
                        {
                            Id = 5,
                            Age = 64,
                            Name = "Squiggle"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
