// <auto-generated />
using System;
using Hiof.DotNetCourse.V2023.Group14.MessagingService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hiof.DotNetCourse.V2023.Group14.MessagingService.Migrations
{
    [DbContext(typeof(MessagingContext))]
    [Migration("20230522081026_AddSeeding")]
    partial class AddSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hiof.DotNetCourse.V2023.Group14.ClassLibrary.Classes.V1.MessageModels.V1ConversationModel", b =>
                {
                    b.Property<string>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ConversationId");

                    b.HasKey("ConversationId");

                    b.ToTable("conversations", "dbo");

                    b.HasData(
                        new
                        {
                            ConversationId = "34eef5ed-35be-408a-a562-95ea91f24fd1"
                        },
                        new
                        {
                            ConversationId = "3ad21e84-4ed0-4483-8ca7-1b29ae06fa00"
                        });
                });

            modelBuilder.Entity("Hiof.DotNetCourse.V2023.Group14.ClassLibrary.Classes.V1.MessageModels.V1Messages", b =>
                {
                    b.Property<string>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("MessageId");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("char(36)")
                        .HasColumnName("ConversationId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId");

                    b.ToTable("messages", "dbo");

                    b.HasData(
                        new
                        {
                            MessageId = "71456bc4-16d4-4b26-9f55-9ce88fa179f6",
                            ConversationId = "34eef5ed-35be-408a-a562-95ea91f24fd1",
                            Date = new DateTime(2023, 5, 19, 11, 13, 28, 830, DateTimeKind.Unspecified).AddTicks(9960),
                            Message = "hey!",
                            Sender = "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                        },
                        new
                        {
                            MessageId = "b24c9d48-79a3-4ef3-bb8e-a978ac4a7170",
                            ConversationId = "34eef5ed-35be-408a-a562-95ea91f24fd1",
                            Date = new DateTime(2023, 5, 19, 11, 9, 59, 399, DateTimeKind.Unspecified).AddTicks(5659),
                            Message = "Hello there :)",
                            Sender = "54af86bf-346a-4cba-b36f-527748e1cb93"
                        },
                        new
                        {
                            MessageId = "d0d316e0-10f3-4460-8571-35c23c3ae15b",
                            ConversationId = "34eef5ed-35be-408a-a562-95ea91f24fd1",
                            Date = new DateTime(2023, 5, 19, 11, 15, 9, 709, DateTimeKind.Unspecified).AddTicks(6212),
                            Message = "nice to hear from you",
                            Sender = "54af86bf-346a-4cba-b36f-527748e1cb93"
                        },
                        new
                        {
                            MessageId = "e3d9836a-208f-4e04-9e22-63b43e6f76e9",
                            ConversationId = "3ad21e84-4ed0-4483-8ca7-1b29ae06fa00",
                            Date = new DateTime(2023, 5, 19, 8, 35, 18, 894, DateTimeKind.Unspecified).AddTicks(6909),
                            Message = "Hello!!",
                            Sender = "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                        });
                });

            modelBuilder.Entity("Hiof.DotNetCourse.V2023.Group14.ClassLibrary.Classes.V1.MessageModels.V1Participant", b =>
                {
                    b.Property<string>("Participant")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConversationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ConversationId");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.HasKey("Participant", "ConversationId");

                    b.HasIndex("ConversationId");

                    b.ToTable("participants", "dbo");

                    b.HasData(
                        new
                        {
                            Participant = "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                            ConversationId = "34eef5ed-35be-408a-a562-95ea91f24fd1",
                            IsRead = false
                        },
                        new
                        {
                            Participant = "54af86bf-346a-4cba-b36f-527748e1cb93",
                            ConversationId = "34eef5ed-35be-408a-a562-95ea91f24fd1",
                            IsRead = true
                        },
                        new
                        {
                            Participant = "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                            ConversationId = "3ad21e84-4ed0-4483-8ca7-1b29ae06fa00",
                            IsRead = true
                        },
                        new
                        {
                            Participant = "e8cc12ba-4df6-4b06-b96e-9ad00a927a93",
                            ConversationId = "3ad21e84-4ed0-4483-8ca7-1b29ae06fa00",
                            IsRead = true
                        });
                });

            modelBuilder.Entity("Hiof.DotNetCourse.V2023.Group14.ClassLibrary.Classes.V1.MessageModels.V1Reactions", b =>
                {
                    b.Property<string>("ReactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ReactionId");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("char(36)")
                        .HasColumnName("MessageId");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ReactionId");

                    b.HasIndex("MessageId");

                    b.ToTable("message_reactions", "dbo");
                });

            modelBuilder.Entity("Hiof.DotNetCourse.V2023.Group14.ClassLibrary.Classes.V1.MessageModels.V1Messages", b =>
                {
                    b.HasOne("Hiof.DotNetCourse.V2023.Group14.ClassLibrary.Classes.V1.MessageModels.V1ConversationModel", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_messages_conversations");
                });

            modelBuilder.Entity("Hiof.DotNetCourse.V2023.Group14.ClassLibrary.Classes.V1.MessageModels.V1Participant", b =>
                {
                    b.HasOne("Hiof.DotNetCourse.V2023.Group14.ClassLibrary.Classes.V1.MessageModels.V1ConversationModel", null)
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hiof.DotNetCourse.V2023.Group14.ClassLibrary.Classes.V1.MessageModels.V1Reactions", b =>
                {
                    b.HasOne("Hiof.DotNetCourse.V2023.Group14.ClassLibrary.Classes.V1.MessageModels.V1Messages", null)
                        .WithMany("Reactions")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_reactions_messages");
                });

            modelBuilder.Entity("Hiof.DotNetCourse.V2023.Group14.ClassLibrary.Classes.V1.MessageModels.V1ConversationModel", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Hiof.DotNetCourse.V2023.Group14.ClassLibrary.Classes.V1.MessageModels.V1Messages", b =>
                {
                    b.Navigation("Reactions");
                });
#pragma warning restore 612, 618
        }
    }
}
